### PR TITLE
VS 2017 15.7 fix, C#7 local function, constructor fix

### PR DESCRIPTION
**Pull request by Liminiens**
This pr fixes vs 2017 15.7 bug #16 and introduces separate settings for class, struct, interface, event, delegate, enum (as new Roslyn API can do that). Also I added separate setting for C# 7 local functions, fixed constructor colorizing, as _constructorType was unused in SemanticColorizer.cs.

So, now it can look like this:

image

### CODE REVIEW

**Comment by GeorgeAlexandria** [comment]
(I'm just a passer who looked this request)

You changed the Roslyn packages version from 1.3.2 to 2.8.0 and changed the visual studio packages from 14.* to 15.*, but I didn't find where you added a some logic to preserve supporting the visual studio 2015 (vs14) (vs14 loads the 1.3.2 packages version in the current domain) or where you describe the broken supporting vs14 if it so. So If I didn't make mistake, this MR can break supporting vs14 in the current state.

**Comment by Liminiens** [comment]
@GeorgeAlexandria oh, thank you, I have rushed a bit with the pr :/. I might close it then, so the support for C# 7 and bug fix would be done separetely and revised.

**Comment by arBmind** [comment]
@Liminiens Thank you for your pull request! It looks really good.

@GeorgeAlexandria Thank you for pointing this out. I will check if it can be made to work.

**Comment by arBmind** [comment]
branch was merged! Thanks for the help!

**Pull request closed without merging**
